from django.core.management.base import BaseCommand
from store.models import Brand, Category, Watch
from decimal import Decimal


class Command(BaseCommand):
    help = 'Seeds the database with luxury watch data'

    def handle(self, *args, **options):
        self.stdout.write('Seeding brands...')
        brands_data = [
            {'name': 'Rolex', 'slug': 'rolex', 'description': 'Swiss luxury watch manufacturer founded in 1905. Known worldwide for precision, reliability, and prestige.', 'founded_year': 1905, 'country': 'Switzerland'},
            {'name': 'Patek Philippe', 'slug': 'patek-philippe', 'description': 'One of the oldest watch manufacturers in the world, producing the most complicated mechanical watches.', 'founded_year': 1839, 'country': 'Switzerland'},
            {'name': 'Audemars Piguet', 'slug': 'audemars-piguet', 'description': 'Swiss luxury watchmaker famous for the Royal Oak collection and avant-garde designs.', 'founded_year': 1875, 'country': 'Switzerland'},
            {'name': 'Omega', 'slug': 'omega', 'description': 'Swiss luxury watchmaker known for the Speedmaster moonwatch and James Bond association.', 'founded_year': 1848, 'country': 'Switzerland'},
            {'name': 'TAG Heuer', 'slug': 'tag-heuer', 'description': 'Swiss luxury watchmaker specializing in sports watches and chronographs.', 'founded_year': 1860, 'country': 'Switzerland'},
            {'name': 'Cartier', 'slug': 'cartier', 'description': 'French luxury goods conglomerate designing and selling jewellery and watches since 1847.', 'founded_year': 1847, 'country': 'France'},
        ]
        brands = {}
        for bd in brands_data:
            b, _ = Brand.objects.get_or_create(slug=bd['slug'], defaults=bd)
            brands[bd['slug']] = b

        self.stdout.write('Seeding categories...')
        cats_data = [
            {'name': 'Dress', 'slug': 'dress', 'description': 'Elegant timepieces for formal occasions'},
            {'name': 'Sport', 'slug': 'sport', 'description': 'Rugged watches built for active lifestyles'},
            {'name': 'Dive', 'slug': 'dive', 'description': 'Water-resistant watches for underwater exploration'},
            {'name': 'Chronograph', 'slug': 'chronograph', 'description': 'Precision stopwatch functionality in a luxury package'},
            {'name': 'Pilot', 'slug': 'pilot', 'description': 'Aviation-inspired timepieces with bold dials'},
        ]
        cats = {}
        for cd in cats_data:
            c, _ = Category.objects.get_or_create(slug=cd['slug'], defaults=cd)
            cats[cd['slug']] = c

        self.stdout.write('Seeding watches...')
        watches_data = [
            {
                'name': 'Submariner Date 41',
                'slug': 'rolex-submariner-date-41',
                'brand': brands['rolex'],
                'category': cats['dive'],
                'description': 'The Rolex Submariner is the reference among divers\' watches. Launched in 1953, it was the first watch waterproof to a depth of 100 metres. The Oyster Perpetual Submariner Date in Oystersteel features a black Cerachrom bezel insert, a black dial, and an Oyster bracelet.',
                'price': Decimal('3250000'),
                'original_price': Decimal('3500000'),
                'case_material': 'Oystersteel',
                'case_diameter': '41 mm',
                'movement': 'Perpetual, mechanical, self-winding (Calibre 3235)',
                'water_resistance': '300 metres / 1,000 feet',
                'strap_material': 'Oystersteel bracelet',
                'dial_color': 'Black',
                'crystal': 'Sapphire with Cyclops lens',
                'power_reserve': 'Approx. 70 hours',
                'reference_number': 'M126610LN-0001',
                'stock': 5,
                'is_featured': True,
                'is_bestseller': True,
            },
            {
                'name': 'Daytona Cosmograph',
                'slug': 'rolex-daytona-cosmograph',
                'brand': brands['rolex'],
                'category': cats['chronograph'],
                'description': 'The Cosmograph Daytona is the ultimate timing instrument for endurance motor racing drivers. This iconic chronograph was designed to meet the demands of professional racing drivers. Its bezel features a tachymetric scale for measuring average speeds up to 400 km/h.',
                'price': Decimal('4850000'),
                'case_material': '18 ct Everose gold',
                'case_diameter': '40 mm',
                'movement': 'Perpetual, mechanical, self-winding (Calibre 4131)',
                'water_resistance': '100 metres / 330 feet',
                'strap_material': 'Oysterflex bracelet',
                'dial_color': 'Meteorite',
                'crystal': 'Sapphire',
                'power_reserve': 'Approx. 72 hours',
                'reference_number': 'M116515LN-0001',
                'stock': 3,
                'is_featured': True,
                'is_new_arrival': True,
            },
            {
                'name': 'Datejust 36',
                'slug': 'rolex-datejust-36',
                'brand': brands['rolex'],
                'category': cats['dress'],
                'description': 'The Datejust is the archetype of the classic watch. Launched in 1945, it was the first self-winding waterproof chronometer wristwatch to display the date in a window at 3 o\'clock on the dial.',
                'price': Decimal('2150000'),
                'original_price': Decimal('2400000'),
                'case_material': 'Oystersteel and 18 ct yellow gold',
                'case_diameter': '36 mm',
                'movement': 'Perpetual, mechanical, self-winding (Calibre 3235)',
                'water_resistance': '100 metres / 330 feet',
                'strap_material': 'Jubilee bracelet',
                'dial_color': 'Champagne-colour',
                'crystal': 'Sapphire with Cyclops lens',
                'power_reserve': 'Approx. 70 hours',
                'reference_number': 'M126233-0015',
                'stock': 8,
                'is_featured': True,
            },
            {
                'name': 'Nautilus 5711/1A',
                'slug': 'patek-philippe-nautilus-5711',
                'brand': brands['patek-philippe'],
                'category': cats['sport'],
                'description': 'The Nautilus has epitomized the elegant sports watch since 1976. Designed by the legendary Gérald Genta, its porthole-inspired case and integrated bracelet have made it one of the most sought-after luxury watches in the world.',
                'price': Decimal('8500000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '40 mm',
                'movement': 'Self-winding mechanical (Calibre 26-330 S C)',
                'water_resistance': '120 metres',
                'strap_material': 'Stainless steel bracelet',
                'dial_color': 'Blue-black gradient',
                'crystal': 'Sapphire',
                'power_reserve': '35-45 hours',
                'reference_number': '5711/1A-010',
                'stock': 2,
                'is_featured': True,
                'is_bestseller': True,
            },
            {
                'name': 'Calatrava 5227R',
                'slug': 'patek-philippe-calatrava-5227r',
                'brand': brands['patek-philippe'],
                'category': cats['dress'],
                'description': 'The Calatrava represents the essence of the round wristwatch. Its harmonious proportions and refined aesthetics make it the embodiment of understated elegance. This reference in rose gold features a stunning silver-gray dial.',
                'price': Decimal('6200000'),
                'case_material': '18K Rose Gold',
                'case_diameter': '39 mm',
                'movement': 'Self-winding mechanical (Calibre 324 S C)',
                'water_resistance': '30 metres',
                'strap_material': 'Alligator leather strap',
                'dial_color': 'Silver-gray lacquered',
                'crystal': 'Sapphire',
                'power_reserve': '35-45 hours',
                'reference_number': '5227R-001',
                'stock': 4,
                'is_featured': True,
                'is_new_arrival': True,
            },
            {
                'name': 'Royal Oak 15500ST',
                'slug': 'audemars-piguet-royal-oak-15500',
                'brand': brands['audemars-piguet'],
                'category': cats['sport'],
                'description': 'The Royal Oak challenged the codes of fine watchmaking when it launched in 1972. Designed by Gérald Genta, its octagonal bezel secured by eight hexagonal screws and "Grande Tapisserie" dial have become icons of horology.',
                'price': Decimal('5800000'),
                'original_price': Decimal('6200000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '41 mm',
                'movement': 'Self-winding (Calibre 4302)',
                'water_resistance': '50 metres',
                'strap_material': 'Stainless steel bracelet',
                'dial_color': 'Blue',
                'crystal': 'Sapphire',
                'power_reserve': '70 hours',
                'reference_number': '15500ST.OO.1220ST.01',
                'stock': 3,
                'is_featured': True,
                'is_bestseller': True,
            },
            {
                'name': 'Speedmaster Moonwatch Professional',
                'slug': 'omega-speedmaster-moonwatch',
                'brand': brands['omega'],
                'category': cats['chronograph'],
                'description': 'The legendary Moonwatch, worn by astronauts on the Moon. The OMEGA Speedmaster Professional Chronograph is an icon of space exploration and one of the most recognised watches in the world.',
                'price': Decimal('575000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '42 mm',
                'movement': 'Manual-winding (Calibre 3861)',
                'water_resistance': '50 metres',
                'strap_material': 'Stainless steel bracelet',
                'dial_color': 'Black step dial',
                'crystal': 'Hesalite',
                'power_reserve': '50 hours',
                'reference_number': '310.30.42.50.01.002',
                'stock': 12,
                'is_featured': True,
                'is_new_arrival': True,
            },
            {
                'name': 'Seamaster Planet Ocean 600M',
                'slug': 'omega-seamaster-planet-ocean',
                'brand': brands['omega'],
                'category': cats['dive'],
                'description': 'The Planet Ocean collection pays tribute to OMEGA\'s pioneering ocean heritage. With a water resistance of 600 metres, it is built for deep sea exploration while maintaining supreme elegance on land.',
                'price': Decimal('680000'),
                'original_price': Decimal('750000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '43.5 mm',
                'movement': 'Co-Axial Master Chronometer (Calibre 8900)',
                'water_resistance': '600 metres',
                'strap_material': 'Stainless steel bracelet',
                'dial_color': 'Black',
                'crystal': 'Sapphire with anti-reflective coating',
                'power_reserve': '60 hours',
                'reference_number': '215.30.44.21.01.001',
                'stock': 7,
                'is_bestseller': True,
            },
            {
                'name': 'Monaco Calibre Heuer 02',
                'slug': 'tag-heuer-monaco-heuer-02',
                'brand': brands['tag-heuer'],
                'category': cats['chronograph'],
                'description': 'The TAG Heuer Monaco is an iconic square-cased chronograph first made famous by Steve McQueen in the 1971 film Le Mans. This modern iteration features the in-house Calibre Heuer 02 movement.',
                'price': Decimal('520000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '39 mm',
                'movement': 'Automatic (Calibre Heuer 02)',
                'water_resistance': '100 metres',
                'strap_material': 'Black leather strap',
                'dial_color': 'Blue',
                'crystal': 'Sapphire',
                'power_reserve': '80 hours',
                'reference_number': 'CBL2111.BA0644',
                'stock': 6,
                'is_featured': True,
            },
            {
                'name': 'Carrera Chronograph',
                'slug': 'tag-heuer-carrera-chronograph',
                'brand': brands['tag-heuer'],
                'category': cats['chronograph'],
                'description': 'Inspired by the legendary Carrera Panamericana road race, the TAG Heuer Carrera combines sporty elegance with exceptional mechanical performance. A true racing chronograph for the modern gentleman.',
                'price': Decimal('435000'),
                'original_price': Decimal('480000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '44 mm',
                'movement': 'Automatic (Calibre Heuer 02)',
                'water_resistance': '100 metres',
                'strap_material': 'Stainless steel bracelet',
                'dial_color': 'Black',
                'crystal': 'Sapphire',
                'power_reserve': '80 hours',
                'reference_number': 'CBN2A1B.BA0643',
                'stock': 9,
                'is_new_arrival': True,
            },
            {
                'name': 'Santos de Cartier Medium',
                'slug': 'cartier-santos-medium',
                'brand': brands['cartier'],
                'category': cats['dress'],
                'description': 'Created by Louis Cartier for aviator Alberto Santos-Dumont in 1904, the Santos was the first modern wristwatch. Its square case with exposed screws has become one of the most recognizable designs in watchmaking.',
                'price': Decimal('750000'),
                'case_material': 'Stainless Steel and 18K Yellow Gold',
                'case_diameter': '35.1 x 41.9 mm',
                'movement': 'Automatic (Calibre 1847 MC)',
                'water_resistance': '100 metres',
                'strap_material': 'Steel and gold bracelet with QuickSwitch system',
                'dial_color': 'Silver',
                'crystal': 'Sapphire',
                'power_reserve': '42 hours',
                'reference_number': 'W2SA0016',
                'stock': 5,
                'is_featured': True,
                'is_new_arrival': True,
            },
            {
                'name': 'Tank Française Medium',
                'slug': 'cartier-tank-francaise',
                'brand': brands['cartier'],
                'category': cats['dress'],
                'description': 'The Tank Française brings a contemporary twist to the classic Tank design with its fluid lines and integrated bracelet. A symbol of Parisian elegance worn by royalty and celebrities worldwide.',
                'price': Decimal('890000'),
                'original_price': Decimal('950000'),
                'case_material': '18K Rose Gold',
                'case_diameter': '32 x 27 mm',
                'movement': 'Quartz',
                'water_resistance': '30 metres',
                'strap_material': '18K Rose Gold bracelet',
                'dial_color': 'Silver with sunburst guilloché',
                'crystal': 'Sapphire',
                'power_reserve': 'N/A (Quartz)',
                'reference_number': 'WGTA0030',
                'stock': 4,
                'is_bestseller': True,
            },
            {
                'name': 'GMT-Master II',
                'slug': 'rolex-gmt-master-ii',
                'brand': brands['rolex'],
                'category': cats['pilot'],
                'description': 'Designed to show the time in two different time zones simultaneously, the GMT-Master II was originally developed for professional airline pilots. The iconic "Pepsi" bezel in Cerachrom sets this reference apart.',
                'price': Decimal('3750000'),
                'case_material': 'Oystersteel',
                'case_diameter': '40 mm',
                'movement': 'Perpetual, mechanical, self-winding (Calibre 3285)',
                'water_resistance': '100 metres',
                'strap_material': 'Jubilee bracelet',
                'dial_color': 'Black',
                'crystal': 'Sapphire with Cyclops lens',
                'power_reserve': 'Approx. 70 hours',
                'reference_number': 'M126710BLRO-0001',
                'stock': 3,
                'is_new_arrival': True,
                'is_bestseller': True,
            },
            {
                'name': 'Royal Oak Offshore Diver',
                'slug': 'ap-royal-oak-offshore-diver',
                'brand': brands['audemars-piguet'],
                'category': cats['dive'],
                'description': 'The Royal Oak Offshore Diver combines the iconic Royal Oak design with professional diving capabilities. Water-resistant to 300 metres, it features an inner rotating bezel and luminescent markers.',
                'price': Decimal('4200000'),
                'case_material': 'Stainless Steel',
                'case_diameter': '42 mm',
                'movement': 'Self-winding (Calibre 4308)',
                'water_resistance': '300 metres',
                'strap_material': 'Rubber strap',
                'dial_color': 'Black Méga Tapisserie',
                'crystal': 'Sapphire',
                'power_reserve': '60 hours',
                'reference_number': '15720ST.OO.A002CA.01',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Aquanaut 5168G',
                'slug': 'patek-philippe-aquanaut-5168g',
                'brand': brands['patek-philippe'],
                'category': cats['sport'],
                'description': 'The Aquanaut represents Patek Philippe\'s sporty-elegant side. Launched in 1997, its rounded octagonal case and tropical strap have made it a modern classic highly coveted by collectors worldwide.',
                'price': Decimal('7200000'),
                'case_material': '18K White Gold',
                'case_diameter': '42.2 mm',
                'movement': 'Self-winding (Calibre 324 S C)',
                'water_resistance': '120 metres',
                'strap_material': 'Composite tropical strap',
                'dial_color': 'Blue-black embossed',
                'crystal': 'Sapphire',
                'power_reserve': '35-45 hours',
                'reference_number': '5168G-001',
                'stock': 1,
                'is_new_arrival': True,
            },
        ]

        for wd in watches_data:
            Watch.objects.get_or_create(slug=wd['slug'], defaults=wd)

        self.stdout.write(self.style.SUCCESS(
            f'Successfully seeded {Brand.objects.count()} brands, '
            f'{Category.objects.count()} categories, '
            f'{Watch.objects.count()} watches'
        ))
